### ISSUE TITLE
captagent built from git has residual data in msg field

### ISSUE THREAD

**Issue by TrevorPH** [sipcapture/captagent#182] opened 2018-09-20 23:55 UTC
I downloaded and built an rpm from the zip file offered from github at the tail end of last week. I fired up the captagent service on a test system installed in a VM where the host has other VMs running SIP servers (asterisk/freeswitch/kamailio). On the host I ran `brcrtl setageing br0 0` so that it acts more like an ethernet hub than a switch and gives me something to capture in my test homer VM.

On most packets sent by captagent to kamailio, I am seeing approximately 16 bytes of residual data in the "msg" column in the mysql database. I checked using `tcpdump port 9061 -i lo -n -nn -l -s0 -X` and can see that the residual data is present in the packets being sent from captagent to kamailio.

An example is:

-- cut here --
SIP/2.0 200 OK
Via: SIP/2.0/UDP x.y.60.71:5060;branch=z9hG4bKFE7D5EDD;received=x.y.60.71;rport=45929
From: <sip:xxxxxxxx@somestring>;tag=05534BEB
To: <sip:xxxxxxxx@somestring>;tag=as20bd7bfb
Call-ID: 5CFA93CA0E0B032E
CSeq: 113966 REGISTER
Server: somestring
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Expires: 180
Contact: <sip:xxxxxxxx@x.y.60.71:5060>;expires=180
Date: Thu, 20 Sep 2018 00:00:00 GMT
Content-Length: 0

-11e8-af96-cd9b8
-- end cut here --

That -11e8-af96-cd9b8 is not meant to be there. The residual data is always different and is difficult to check that it's always 16 bytes since it sometimes contains e.g. embedded carriage returns etc. I think it is 16 bytes but wouldn't bet anything on it.

This appears to be something that only happens when /etc/captagent/transport_hep.xml is configured to use version 3. If I change this to <param name="version" value="2"/> then the problem goes away.

<?xml version="1.0"?>
<document type="captagent_module/xml">
    <module name="transport_hep" description="HEP Protocol" serial="2014010402">
        <profile name="hepsocket" description="Transport HEP" enable="true" serial="2014010402">
            <settings>
                <param name="version" value="2"/>
                <param name="capture-host" value="127.0.0.1"/>
                <param name="capture-port" value="9061"/>
                <param name="capture-proto" value="udp"/>
                <param name="capture-id" value="2001"/>
                <param name="capture-password" value="myhep"/>
                <param name="payload-compression" value="false"/>
            </settings>
        </profile>
    </module>
</document>

is now working correctly as far as I can see.

**Comment by TrevorPH** [comment] 2018-09-21 00:00
hmm, that ate my xml content! Pretty pointless posting it anyway since it's what came out of the build process and was set to use param name="version" value="3" and changing that to value="2" has made the problem go away,.

**Comment by kYroL01** [comment] 2019-05-15 10:32
I think the problem is fixed with latest release. Reopen if necessary

**Closed by kYroL01** 2019-05-15 10:32 UTC
