### ISSUE TITLE
Not getting entire SIP capture MIME 

### ISSUE THREAD

**Issue by Akashm027** [sipcapture/captagent#185] opened 2018-10-22 07:36 UTC
Hi ,
I am capturing SIP traces using Homer but in homer web interface , I don't see complete SDP offer.As displayed in image ..I am getting data till t and not after that

![image](https://user-images.githubusercontent.com/42645069/47281966-fee8a580-d5fa-11e8-811f-51615ec35e64.png)

After exploring , found out that we need to fragment sip capture to capture entire packet by setting realsm flag to True in socket_pcap.cfg but after doing this we don't get any SIP capture which has been fragmented .
Need help in capturing entire MIMe data or capturing fragmented data?

**Comment by Akashm027** [comment] 2018-10-24 13:49
took tcpdump at homer server . I am getting correct/entire data .I guess problem is when kamailio is storing info in tables?

**Comment by btriller** [comment] 2018-10-24 14:21
Check size of msg column in homer_data database.

**Comment by rs03** [comment] 2018-12-03 12:43
Was facing the same issue and got it resolved by editing reasm to true  and filter range as mentioned below socket_pcap.xml

                <param name="reasm" value="true"/>
                <param name="tcpdefrag" value="false"/>
                <param name="capture-plan" value="sip_capture_plan.cfg"/>
                <param name="filter">
                    <value>portrange 5060-5091 or ip[6:2]</value>

**Comment by kYroL01** [comment] 2018-12-04 15:43
this issue is a duplicate of this https://github.com/sipcapture/captagent/issues/184.
Reopen if necessary

**Closed by kYroL01** 2018-12-04 15:43 UTC
